Switches Java invocation to use variable expansion
When JAVA_OPTS or other variables need to be passed, any dynamic arguments are not expanded.

This means you get something like this:

```
Defaulted container "registration-service" out of: registration-service, install-oneagent (init), configure-truststore (init)
Error: Could not find or load main class $JAVA_OPTS
Caused by: java.lang.ClassNotFoundException: $JAVA_OPTS
```
which is obviously not ideal.

Instead we need the shell form for variable expansion.